### ISSUE TITLE
Post request not working

### ISSUE THREAD

**Issue by ShahrozTanveer** [slim-hmidi/deno-employees-api#1]
` const body = await (c.body());`
returns nothing

**Comment by slim-hmidi** [comment]
I test it and it works. Can you share with me what you did or how test it? did you choose `form-data` or `raw` option when you tested with postman?

**Comment by ShahrozTanveer** [comment]
index.ts
`import { Application } from "https://deno.land/x/abc@v1.0.0-rc2/mod.ts";
import "https://deno.land/x/denv/mod.ts";
import {
  fetchAllPost,
  createPost,
  fetchOnePost,
} from "./controllers/post.ts";
const app = new Application();

app.get("/post", fetchAllPost)
  .post("/post", createPost)
  .get("/post/:id", fetchOnePost)
  .start({ port: 5000 });

console.log(`server listening on http://localhost:5000 `);
`
post.ts
`import {
  HandlerFunc,
  Context,
} from "https://deno.land/x/abc@v1.0.0-rc2/mod.ts";
import db from "../config/db.ts";

const database = db.getDatabase;
const post = database.collection("post");
console.log("test");
interface Post {
  _id: {
    $oid: string;
  };
  title: string;
  content: string;
  author: string;
  date: Date;
}

const createPost: HandlerFunc = async (c: Context) => {
  console.log("test ::: here");
  try {
    const body = await (c.body());
    console.log("body");

    if (!Object.keys(body).length) {
      return c.string("Request body can not be empty!", 400);
    }
    const { title, content, author } = body;
    const date = Date.now();
    console.log(`${date} here`);
    const insertedPost = await post.insertOne({
      title,
      content,
      author,
      date,
    });
    console.log(`${insertedPost}:: post`);
    return c.json(insertedPost, 201);
  } catch (error) {
    return c.json(error, 500);
  }
};

const fetchAllPost: HandlerFunc = async (c: Context) => {
  try {
    const fetchedPosts: Post[] = await post.find();

    if (fetchedPosts) {
      const list = fetchedPosts.length
        ? fetchedPosts.map((p) => {
          const { _id: { $oid }, title, content, author, date } = p;
          return { id: $oid, title, content, author, date };
        })
        : [];
      return c.json(list, 200);
    }
  } catch (error) {
    console.log(c);
    return c.json(error, 500);
  }
};

const fetchOnePost: HandlerFunc = async (c: Context) => {
  try {
    const { id } = c.params as { id: string };

    const fetchedPost = await post.findOne({ _id: { "$oid": id } });

    if (fetchedPost) {
      const { _id: { $oid }, title, content, author, date } = fetchedPost;
      return c.json({ id: $oid, title, content, author, date }, 200);
    }

    return c.string("Post not found", 404);
  } catch (error) {
    return c.json(error, 500);
  }
};

export { createPost, fetchAllPost, fetchOnePost };
`

**Comment by slim-hmidi** [comment]
@ShahrozTanveer  how did you test the api in Postman? 
When you tested the post api did you choose `form-data` option or `raw` because the `Context.body` parse a json object not form-data.
Check this [body()](https://github.com/zhmushan/abc/blob/v1.0.0-rc2/context.ts#L62)

**Comment by slim-hmidi** [comment]
@ShahrozTanveer I added a condition to check if the content-type is `application/json` or not. If you are using postman to test the api, check `raw` option when you create the body, because ` abc` parse a json in the `body` method, so the option `form-data` and `x-www-form-urlencoded` will throw an error.

**Comment by ShahrozTanveer** [comment]
this is index.ts
import { Application } from "https://deno.land/x/abc@v1.0.0-rc2/mod.ts";
import { Context } from "https://deno.land/x/abc@v1.0.0-rc2/mod.ts";
const app = new Application();
app.get("/", async (c: Context) => {
  try {
    return c.json({ msg: "hello this is index" }, 201);
  } catch (error) {
    return c.json(error, 500);
  }
})
  .post("/", async (c: Context) => {
    try {
      const body = await (c.body());
      console.log(`this is body ${body}`);
      return c.json(body, 200);
    } catch (error) {
      return c.json(error, 500);
    }
  })
  .start({ port: 5000 });
console.log(`server listening on http://localhost:5000 `);




Postman:
![raw_post](https://user-images.githubusercontent.com/31120765/82146578-bd66bd80-9864-11ea-97c8-ca93d8d7311d.png)
